### PR TITLE
Allow specifying a proxy in request options (#21).

### PR DESCRIPTION
**Pull request by dparpyani**
For #21

### CODE REVIEW

**Comment by dparpyani** [comment]
@philnash hm are the ruby-head failures expected?

**Comment by philnash** [comment]
Ah, yes, I think so. I have already excluded Rails 5/Ruby 3 tests, because they do not work. These failures are in Rails 5 (well, active record 5) and Ruby head, so are expected. I don't think you have anything to worry about there.

(Side note: it's funny to me that Rails 4 seems to work with Ruby 3, but Rails 5 doesn't. 🤷‍♂️)

**Comment by dparpyani** [comment]
Gotcha, thanks. Yeah, the Rails 4 compatibility with Ruby 3 is funny indeed!

Let me know if I missed something in this PR. Also, once it is merged, I would appreciate a release so we can start using it in our codebase 😄

**Comment by dparpyani** [comment]
@philnash 👋 any ETA on a review?

**Comment by dparpyani** [comment]
Thanks!

**Pull request merged**
