### PR TITLE
Support calling the library asynchronously

### PR DESCRIPTION
**Pull request by paprikati**
This allows callers to store the hashed password, and then call the pwned API at some later stage (e.g. to enqueue the job)

resolves https://github.com/philnash/pwned/issues/19

### CODE REVIEW

**Comment by philnash** [comment]
Awesome, I will take a swing through this today. Thanks.

**Comment by philnash** [comment]
Thanks @paprikati! This has just been released as version 2.1.0.

**Comment by paprikati** [comment]
Great - thanks @philnash !

**Comment by tvanderpol** [comment]
This is a really nice change, thanks for the effort, @philnash & @paprikati ! 👍

**Pull request merged**
